config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  scope "/(:locale)", defaults: {locale: 'en'}, constraints: { locale: /en|es/ } do

    devise_for :usuarios, skip: [:omniauth_callbacks]
    get 'home/index'

    root "home#index"

  end

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates_presence_of :firstname
  validates_presence_of :lastname
  validates_presence_of :birthday

  def self.find_or_create_by_omniauth(auth)
  	usuario = Usuario.where(provider: auth[:provider], uid: auth[:uid]).first
  	unless usuario
  		usuario = Usuario.create(
  			firstname: auth[:firstname],
  			lastname: auth[:lastname],
  			username: auth[:username],
  			email: auth[:email],
  			uid: auth[:uid],
  			provider: auth[:provider],
  			password: Devise.friendly_token[0,20]
  		)
  	else
  		usuario = usuario
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  before_action :configure_permitted_parameters, if: :devise_controller?

  def set_locale
  	I18n.locale = params[:locale]
  end

  def default_url_options (options = {})
    {locale: I18n.locale}
  end

  def after_sign_in_path_for (resource_or_scope)
    root_url(locale: I18n.locale)
  end

  def after_sign_out_path_for (resource_or_scope)
    root_url(locale: I18n.locale)
  end

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname, :lastname, :username, :phone, :address, :country, :zipcode, :birthday, :email, :password) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:firstname, :lastname, :username, :phone, :address, :country, :zipcode, :birthday, :email, :password, :current_password) }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
	def facebook
		auth = request.env["omniauth.auth"]
		data = {
      		firstname: auth.info.first_name,
      		lastname: auth.info.last_name,
      		email: auth.info.email,
      		username: auth.info.nickname,
      		city: auth.info.city,
      		country: auth.info.country,
      		provider: auth.provider,
      		uid: auth.uid,
      		locale: auth.extra.raw_info.locale,
      		verified: auth.extra.raw_info.verified
		}

		@usuario = Usuario.find_or_create_by_omniauth(data)

		if @usuario.persisted?
			sign_in_and_redirect @usuario, event: :authentication, locale: "es"
		else
			session[:omniauth_errors] = @usuario.errors.full_messages.to_sentence unless @usuario.save

			session[:facebook_data] = data

			redirect_to new_usuario_registration_url
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_email_oauth
		if session[:facebook_data]
			session[:facebook_data]["email"]
		else
			""
		end
	end
	def get_firstname_oauth
		if session[:facebook_data]
			session[:facebook_data]["firstname"]
		else
			""
		end
	end
	def get_lastname_oauth
		if session[:facebook_data]
			session[:facebook_data]["lastname"]
		else
			""
		end
	end
	def get_username_oauth
		if session[:facebook_data]
			session[:facebook_data]["username"]
		else
			""
		end
	end
	def get_country_oauth
		if session[:facebook_data]
			session[:facebook_data]["country"]
		else
			""
		end
	end
	def get_city_oauth
		if session[:facebook_data]
			session[:facebook_data]["city"]
		else
			""
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
    <h1><i class="fa fa-diamond fa-fw"></i><%= t '.title' %></h1>
    <h1><i class="fa fa-whatsapp fa-fw" style="color: green; background-color: #fff"></i><%= t '.title' %></h1>
    <h1><i class="fa fa-line fa-fw" style="color: green"></i><%= t '.title' %></h1>
    <p><%= t '.description' %></p>
    <p><a class="btn btn-primary btn-lg">Learn more</a></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>App</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<header>
			<nav>
				<div class="navbar navbar-warning">
		            <div class="navbar-header">
		                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
		                    <span class="icon-bar"></span>
		                    <span class="icon-bar"></span>
		                    <span class="icon-bar"></span>
		                </button>
		                <%= link_to t("nav.root"), root_url(locale: I18n.locale), class: "navbar-brand" %>
		            </div>
			        <div class="navbar-collapse collapse navbar-warning-collapse">
			            <ul class="nav navbar-nav">
			                <% if usuario_signed_in? %>
							<li>
								<% id = current_usuario.id %>
								<%= link_to t("nav.edit"), edit_usuario_registration_url(locale: I18n.locale), data: id %>
							</li>
							<li>
								<%= link_to t("nav.close"), destroy_usuario_session_path(locale: I18n.locale), method: :delete %>
							</li>
							<% else %>
							<li>
								<%= link_to t("nav.login"), new_usuario_session_path(locale: I18n.locale) %>
							</li>
							<li>
								<%= link_to t("nav.signup"), new_usuario_registration_path(locale: I18n.locale) %>
							</li>
							<% end %>
			            </ul>
			            <ul class="nav navbar-nav navbar-right">
			                <li>
								<%= link_to "Español", locale: "es" %>
							</li>
							<li style="margin-right: 20px">
								<%= link_to "Ingles", locale: "en" %>
							</li>
			            </ul>
			        </div>
	        	</div>
        	</nav>
		</header>

		 <p class="notice" style="<%= "display:none;" if notice.nil? %>"><%= notice %></p>
		 <p class="alerta" style="<%= "display:none;" if alert.nil? %>"><%= alert %></p>
		<div class="container" style="margin-top: 30px">
			<%= yield %>
		</div>
	</body>
	<script type="text/javascript">
		$.material.init();

		function validateCheckbox()
		{
		    if( $('#checkbox').attr('checked')){
		      alert("you have to accept the terms first");
		    }
		}
	</script>
</html>